<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('code' => 'US', 'name_en' => 'United States'),
            array('code' => 'CA', 'name_en' => 'Canada'),
            array('code' => 'AF', 'name_en' => 'Afghanistan'),
            array('code' => 'AL', 'name_en' => 'Albania'),
            array('code' => 'DZ', 'name_en' => 'Algeria'),
            array('code' => 'AS', 'name_en' => 'American Samoa'),
            array('code' => 'AD', 'name_en' => 'Andorra'),
            array('code' => 'AO', 'name_en' => 'Angola'),
            array('code' => 'AI', 'name_en' => 'Anguilla'),
            array('code' => 'AQ', 'name_en' => 'Antarctica'),
            array('code' => 'AG', 'name_en' => 'Antigua and/or Barbuda'),
            array('code' => 'AR', 'name_en' => 'Argentina'),
            array('code' => 'AM', 'name_en' => 'Armenia'),
            array('code' => 'AW', 'name_en' => 'Aruba'),
            array('code' => 'AU', 'name_en' => 'Australia'),
            array('code' => 'AT', 'name_en' => 'Austria'),
            array('code' => 'AZ', 'name_en' => 'Azerbaijan'),
            array('code' => 'BS', 'name_en' => 'Bahamas'),
            array('code' => 'BH', 'name_en' => 'Bahrain'),
            array('code' => 'BD', 'name_en' => 'Bangladesh'),
            array('code' => 'BB', 'name_en' => 'Barbados'),
            array('code' => 'BY', 'name_en' => 'Belarus'),
            array('code' => 'BE', 'name_en' => 'Belgium'),
            array('code' => 'BZ', 'name_en' => 'Belize'),
            array('code' => 'BJ', 'name_en' => 'Benin'),
            array('code' => 'BM', 'name_en' => 'Bermuda'),
            array('code' => 'BT', 'name_en' => 'Bhutan'),
            array('code' => 'BO', 'name_en' => 'Bolivia'),
            array('code' => 'BA', 'name_en' => 'Bosnia and Herzegovina'),
            array('code' => 'BW', 'name_en' => 'Botswana'),
            array('code' => 'BV', 'name_en' => 'Bouvet Island'),
            array('code' => 'BR', 'name_en' => 'Brazil'),
            array('code' => 'IO', 'name_en' => 'British lndian Ocean Territory'),
            array('code' => 'BN', 'name_en' => 'Brunei Darussalam'),
            array('code' => 'BG', 'name_en' => 'Bulgaria'),
            array('code' => 'BF', 'name_en' => 'Burkina Faso'),
            array('code' => 'BI', 'name_en' => 'Burundi'),
            array('code' => 'KH', 'name_en' => 'Cambodia'),
            array('code' => 'CM', 'name_en' => 'Cameroon'),
            array('code' => 'CV', 'name_en' => 'Cape Verde'),
            array('code' => 'KY', 'name_en' => 'Cayman Islands'),
            array('code' => 'CF', 'name_en' => 'Central African Republic'),
            array('code' => 'TD', 'name_en' => 'Chad'),
            array('code' => 'CL', 'name_en' => 'Chile'),
            array('code' => 'CN', 'name_en' => 'China'),
            array('code' => 'CX', 'name_en' => 'Christmas Island'),
            array('code' => 'CC', 'name_en' => 'Cocos (Keeling) Islands'),
            array('code' => 'CO', 'name_en' => 'Colombia'),
            array('code' => 'KM', 'name_en' => 'Comoros'),
            array('code' => 'CG', 'name_en' => 'Congo'),
            array('code' => 'CK', 'name_en' => 'Cook Islands'),
            array('code' => 'CR', 'name_en' => 'Costa Rica'),
            array('code' => 'HR', 'name_en' => 'Croatia (Hrvatska)'),
            array('code' => 'CU', 'name_en' => 'Cuba'),
            array('code' => 'CY', 'name_en' => 'Cyprus'),
            array('code' => 'CZ', 'name_en' => 'Czech Republic'),
            array('code' => 'CD', 'name_en' => 'Democratic Republic of Congo'),
            array('code' => 'DK', 'name_en' => 'Denmark'),
            array('code' => 'DJ', 'name_en' => 'Djibouti'),
            array('code' => 'DM', 'name_en' => 'Dominica'),
            array('code' => 'DO', 'name_en' => 'Dominican Republic'),
            array('code' => 'TP', 'name_en' => 'East Timor'),
            array('code' => 'EC', 'name_en' => 'Ecudaor'),
            array('code' => 'EG', 'name_en' => 'Egypt'),
            array('code' => 'SV', 'name_en' => 'El Salvador'),
            array('code' => 'GQ', 'name_en' => 'Equatorial Guinea'),
            array('code' => 'ER', 'name_en' => 'Eritrea'),
            array('code' => 'EE', 'name_en' => 'Estonia'),
            array('code' => 'ET', 'name_en' => 'Ethiopia'),
            array('code' => 'FK', 'name_en' => 'Falkland Islands (Malvinas)'),
            array('code' => 'FO', 'name_en' => 'Faroe Islands'),
            array('code' => 'FJ', 'name_en' => 'Fiji'),
            array('code' => 'FI', 'name_en' => 'Finland'),
            array('code' => 'FR', 'name_en' => 'France'),
            array('code' => 'FX', 'name_en' => 'France, Metropolitan'),
            array('code' => 'GF', 'name_en' => 'French Guiana'),
            array('code' => 'PF', 'name_en' => 'French Polynesia'),
            array('code' => 'TF', 'name_en' => 'French Southern Territories'),
            array('code' => 'GA', 'name_en' => 'Gabon'),
            array('code' => 'GM', 'name_en' => 'Gambia'),
            array('code' => 'GE', 'name_en' => 'Georgia'),
            array('code' => 'DE', 'name_en' => 'Germany'),
            array('code' => 'GH', 'name_en' => 'Ghana'),
            array('code' => 'GI', 'name_en' => 'Gibraltar'),
            array('code' => 'GR', 'name_en' => 'Greece'),
            array('code' => 'GL', 'name_en' => 'Greenland'),
            array('code' => 'GD', 'name_en' => 'Grenada'),
            array('code' => 'GP', 'name_en' => 'Guadeloupe'),
            array('code' => 'GU', 'name_en' => 'Guam'),
            array('code' => 'GT', 'name_en' => 'Guatemala'),
            array('code' => 'GN', 'name_en' => 'Guinea'),
            array('code' => 'GW', 'name_en' => 'Guinea-Bissau'),
            array('code' => 'GY', 'name_en' => 'Guyana'),
            array('code' => 'HT', 'name_en' => 'Haiti'),
            array('code' => 'HM', 'name_en' => 'Heard and Mc Donald Islands'),
            array('code' => 'HN', 'name_en' => 'Honduras'),
            array('code' => 'HK', 'name_en' => 'Hong Kong'),
            array('code' => 'HU', 'name_en' => 'Hungary'),
            array('code' => 'IS', 'name_en' => 'Iceland'),
            array('code' => 'IN', 'name_en' => 'India'),
            array('code' => 'ID', 'name_en' => 'Indonesia'),
            array('code' => 'IR', 'name_en' => 'Iran (Islamic Republic of)'),
            array('code' => 'IQ', 'name_en' => 'Iraq'),
            array('code' => 'IE', 'name_en' => 'Ireland'),
            array('code' => 'IL', 'name_en' => 'Israel'),
            array('code' => 'IT', 'name_en' => 'Italy'),
            array('code' => 'CI', 'name_en' => 'Ivory Coast'),
            array('code' => 'JM', 'name_en' => 'Jamaica'),
            array('code' => 'JP', 'name_en' => 'Japan'),
            array('code' => 'JO', 'name_en' => 'Jordan'),
            array('code' => 'KZ', 'name_en' => 'Kazakhstan'),
            array('code' => 'KE', 'name_en' => 'Kenya'),
            array('code' => 'KI', 'name_en' => 'Kiribati'),
            array('code' => 'KP', 'name_en' => 'Korea, Democratic People\'s Republic of'),
            array('code' => 'KR', 'name_en' => 'Korea, Republic of'),
            array('code' => 'KW', 'name_en' => 'Kuwait'),
            array('code' => 'KG', 'name_en' => 'Kyrgyzstan'),
            array('code' => 'LA', 'name_en' => 'Lao People\'s Democratic Republic'),
            array('code' => 'LV', 'name_en' => 'Latvia'),
            array('code' => 'LB', 'name_en' => 'Lebanon'),
            array('code' => 'LS', 'name_en' => 'Lesotho'),
            array('code' => 'LR', 'name_en' => 'Liberia'),
            array('code' => 'LY', 'name_en' => 'Libyan Arab Jamahiriya'),
            array('code' => 'LI', 'name_en' => 'Liechtenstein'),
            array('code' => 'LT', 'name_en' => 'Lithuania'),
            array('code' => 'LU', 'name_en' => 'Luxembourg'),
            array('code' => 'MO', 'name_en' => 'Macau'),
            array('code' => 'MK', 'name_en' => 'Macedonia'),
            array('code' => 'MG', 'name_en' => 'Madagascar'),
            array('code' => 'MW', 'name_en' => 'Malawi'),
            array('code' => 'MY', 'name_en' => 'Malaysia'),
            array('code' => 'MV', 'name_en' => 'Maldives'),
            array('code' => 'ML', 'name_en' => 'Mali'),
            array('code' => 'MT', 'name_en' => 'Malta'),
            array('code' => 'MH', 'name_en' => 'Marshall Islands'),
            array('code' => 'MQ', 'name_en' => 'Martinique'),
            array('code' => 'MR', 'name_en' => 'Mauritania'),
            array('code' => 'MU', 'name_en' => 'Mauritius'),
            array('code' => 'TY', 'name_en' => 'Mayotte'),
            array('code' => 'MX', 'name_en' => 'Mexico'),
            array('code' => 'FM', 'name_en' => 'Micronesia, Federated States of'),
            array('code' => 'MD', 'name_en' => 'Moldova, Republic of'),
            array('code' => 'MC', 'name_en' => 'Monaco'),
            array('code' => 'MN', 'name_en' => 'Mongolia'),
            array('code' => 'MS', 'name_en' => 'Montserrat'),
            array('code' => 'MA', 'name_en' => 'Morocco'),
            array('code' => 'MZ', 'name_en' => 'Mozambique'),
            array('code' => 'MM', 'name_en' => 'Myanmar'),
            array('code' => 'NA', 'name_en' => 'Namibia'),
            array('code' => 'NR', 'name_en' => 'Nauru'),
            array('code' => 'NP', 'name_en' => 'Nepal'),
            array('code' => 'NL', 'name_en' => 'Netherlands'),
            array('code' => 'AN', 'name_en' => 'Netherlands Antilles'),
            array('code' => 'NC', 'name_en' => 'New Caledonia'),
            array('code' => 'NZ', 'name_en' => 'New Zealand'),
            array('code' => 'NI', 'name_en' => 'Nicaragua'),
            array('code' => 'NE', 'name_en' => 'Niger'),
            array('code' => 'NG', 'name_en' => 'Nigeria'),
            array('code' => 'NU', 'name_en' => 'Niue'),
            array('code' => 'NF', 'name_en' => 'Norfork Island'),
            array('code' => 'MP', 'name_en' => 'Northern Mariana Islands'),
            array('code' => 'NO', 'name_en' => 'Norway'),
            array('code' => 'OM', 'name_en' => 'Oman'),
            array('code' => 'PK', 'name_en' => 'Pakistan'),
            array('code' => 'PW', 'name_en' => 'Palau'),
            array('code' => 'PA', 'name_en' => 'Panama'),
            array('code' => 'PG', 'name_en' => 'Papua New Guinea'),
            array('code' => 'PY', 'name_en' => 'Paraguay'),
            array('code' => 'PE', 'name_en' => 'Peru'),
            array('code' => 'PH', 'name_en' => 'Philippines'),
            array('code' => 'PN', 'name_en' => 'Pitcairn'),
            array('code' => 'PL', 'name_en' => 'Poland'),
            array('code' => 'PT', 'name_en' => 'Portugal'),
            array('code' => 'PR', 'name_en' => 'Puerto Rico'),
            array('code' => 'QA', 'name_en' => 'Qatar'),
            array('code' => 'SS', 'name_en' => 'Republic of South Sudan'),
            array('code' => 'RE', 'name_en' => 'Reunion'),
            array('code' => 'RO', 'name_en' => 'Romania'),
            array('code' => 'RU', 'name_en' => 'Russian Federation'),
            array('code' => 'RW', 'name_en' => 'Rwanda'),
            array('code' => 'KN', 'name_en' => 'Saint Kitts and Nevis'),
            array('code' => 'LC', 'name_en' => 'Saint Lucia'),
            array('code' => 'VC', 'name_en' => 'Saint Vincent and the Grenadines'),
            array('code' => 'WS', 'name_en' => 'Samoa'),
            array('code' => 'SM', 'name_en' => 'San Marino'),
            array('code' => 'ST', 'name_en' => 'Sao Tome and Principe'),
            array('code' => 'SA', 'name_en' => 'Saudi Arabia'),
            array('code' => 'SN', 'name_en' => 'Senegal'),
            array('code' => 'RS', 'name_en' => 'Serbia'),
            array('code' => 'SC', 'name_en' => 'Seychelles'),
            array('code' => 'SL', 'name_en' => 'Sierra Leone'),
            array('code' => 'SG', 'name_en' => 'Singapore'),
            array('code' => 'SK', 'name_en' => 'Slovakia'),
            array('code' => 'SI', 'name_en' => 'Slovenia'),
            array('code' => 'SB', 'name_en' => 'Solomon Islands'),
            array('code' => 'SO', 'name_en' => 'Somalia'),
            array('code' => 'ZA', 'name_en' => 'South Africa'),
            array('code' => 'GS', 'name_en' => 'South Georgia South Sandwich Islands'),
            array('code' => 'ES', 'name_en' => 'Spain'),
            array('code' => 'LK', 'name_en' => 'Sri Lanka'),
            array('code' => 'SH', 'name_en' => 'St. Helena'),
            array('code' => 'PM', 'name_en' => 'St. Pierre and Miquelon'),
            array('code' => 'SD', 'name_en' => 'Sudan'),
            array('code' => 'SR', 'name_en' => 'Suriname_en'),
            array('code' => 'SJ', 'name_en' => 'Svalbarn and Jan Mayen Islands'),
            array('code' => 'SZ', 'name_en' => 'Swaziland'),
            array('code' => 'SE', 'name_en' => 'Sweden'),
            array('code' => 'CH', 'name_en' => 'Switzerland'),
            array('code' => 'SY', 'name_en' => 'Syrian Arab Republic'),
            array('code' => 'TW', 'name_en' => 'Taiwan'),
            array('code' => 'TJ', 'name_en' => 'Tajikistan'),
            array('code' => 'TZ', 'name_en' => 'Tanzania, United Republic of'),
            array('code' => 'TH', 'name_en' => 'Thailand'),
            array('code' => 'TG', 'name_en' => 'Togo'),
            array('code' => 'TK', 'name_en' => 'Tokelau'),
            array('code' => 'TO', 'name_en' => 'Tonga'),
            array('code' => 'TT', 'name_en' => 'Trinidad and Tobago'),
            array('code' => 'TN', 'name_en' => 'Tunisia'),
            array('code' => 'TR', 'name_en' => 'Turkey'),
            array('code' => 'TM', 'name_en' => 'Turkmenistan'),
            array('code' => 'TC', 'name_en' => 'Turks and Caicos Islands'),
            array('code' => 'TV', 'name_en' => 'Tuvalu'),
            array('code' => 'UG', 'name_en' => 'Uganda'),
            array('code' => 'UA', 'name_en' => 'Ukraine'),
            array('code' => 'AE', 'name_en' => 'United Arab Emirates'),
            array('code' => 'GB', 'name_en' => 'United Kingdom'),
            array('code' => 'UM', 'name_en' => 'United States minor outlying islands'),
            array('code' => 'UY', 'name_en' => 'Uruguay'),
            array('code' => 'UZ', 'name_en' => 'Uzbekistan'),
            array('code' => 'VU', 'name_en' => 'Vanuatu'),
            array('code' => 'VA', 'name_en' => 'Vatican City State'),
            array('code' => 'VE', 'name_en' => 'Venezuela'),
            array('code' => 'VN', 'name_en' => 'Vietnam'),
            array('code' => 'VG', 'name_en' => 'Virgin Islands (British)'),
            array('code' => 'VI', 'name_en' => 'Virgin Islands (U.S.)'),
            array('code' => 'WF', 'name_en' => 'Wallis and Futuna Islands'),
            array('code' => 'EH', 'name_en' => 'Western Sahara'),
            array('code' => 'YE', 'name_en' => 'Yemen'),
            array('code' => 'YU', 'name_en' => 'Yugoslavia'),
            array('code' => 'ZR', 'name_en' => 'Zaire'),
            array('code' => 'ZM', 'name_en' => 'Zambia'),
            array('code' => 'ZW', 'name_en' => 'Zimbabwe'),
        );

        $insertSql = [];
        foreach($countries as $key=>$country){
        	$insertSql[] = "(\"".($key+1)."\", \"".implode('", "', $country).'")';
        }

        DB::insert(
        	"insert into countries (id, code, name_en) values " .
	        implode(', ', $insertSql).
	        " on duplicate key update code = values(code), name_en = values(name_en), name_ar = values(`name_ar`)"

        );
    }


}
